### ISSUE TITLE
models_server.py returns error

### ISSUE THREAD

**Issue by TLpigff** [microsoft/JARVIS#73] opened 2023-04-06 13:17 UTC
I Run `python3 models_server.py --config config.yaml`  but Got
```
 Traceback (most recent call last):
  File "/Users/bytedance/miniconda3/envs/jarvis/lib/python3.8/site-packages/transformers/modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/Users/bytedance/miniconda3/envs/jarvis/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/bytedance/miniconda3/envs/jarvis/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "models_server.py", line 342, in <module>
    pipes = load_pipes(local_deployment)
  File "models_server.py", line 87, in load_pipes
    "model": VisionEncoderDecoderModel.from_pretrained(f"{local_fold}/nlpconnect/vit-gpt2-image-captioning"),
  File "/Users/bytedance/miniconda3/envs/jarvis/lib/python3.8/site-packages/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py", line 363, in from_pretrained
    return super().from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/Users/bytedance/miniconda3/envs/jarvis/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2477, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/Users/bytedance/miniconda3/envs/jarvis/lib/python3.8/site-packages/transformers/modeling_utils.py", line 420, in load_state_dict
    raise OSError(
```

Is there anyone know this?

**Comment by Daeda1used** [comment] 2023-04-06 13:25
Hi @TLpigff

I believe I have been in your place and my solution is as follows:

The reason why you meet this error is most likely you haven't successfully run the "download,sh" script because your environment does not get `git-lfs` installed or working properly.

Try install git-lfs by type followed command:
` sudo apt-get install git-lfs`

Then re-run the 'download.sh' script. 

Hope it works for you.

**Comment by TLpigff** [comment] 2023-04-06 13:31
Thanks I just forget to rerun download.sh

**Comment by StillKeepTry** [comment] 2023-04-06 14:28
@TLpigff Would you close this issue if your problem is solved?

**Comment by rizified** [comment] 2023-04-06 15:03
This solved my issue of model downloading!
Thanks maybe we can add it in main Readme

**Comment by tosaddler** [comment] 2023-04-06 16:12
I have also been trying to track down the cause of this issue, and it seems it has to do with the structure of `download.sh` being changed. If you try and run the file manually with `sh download.sh`, then you get the error:

```
(jarvis) root@569f116529ef:/JARVIS/server/models# sh download.sh
download.sh: 4: download.sh: Syntax error: "(" unexpected
```

In the quickstart guide it states that you should be using `sh`, but at the top of the `download.sh` file it actually calls for `bash`. So on top of needing `git-lfs` installed, I was able to get the download script working using `bash download.sh`.

**Closed** 2023-04-06 21:16 UTC
